//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO_TONKHO
    {
        public BAOCAO_TONKHO()
        {
            this.CT_BAOCAO_TONKHO = new HashSet<CT_BAOCAO_TONKHO>();
        }
    
        public string MaBaoCao { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaNguoiLap { get; set; }
        public int TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<CT_BAOCAO_TONKHO> CT_BAOCAO_TONKHO { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
