//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVITINH
    {
        public DONVITINH()
        {
            this.LINHKIENs = new HashSet<LINHKIEN>();
        }
    
        public string MaDonViTinh { get; set; }
        public string TenDonViTinh { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<LINHKIEN> LINHKIENs { get; set; }
    }
}
