//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_NHAPHANG
    {
        public HOADON_NHAPHANG()
        {
            this.CT_HOADON_NHAPHANG = new HashSet<CT_HOADON_NHAPHANG>();
        }
    
        public string MaHoaDon { get; set; }
        public string MaNhaCungCap { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string MaNguoiLap { get; set; }
        public decimal TongTien { get; set; }
        public int TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<CT_HOADON_NHAPHANG> CT_HOADON_NHAPHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
