//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINHKIEN
    {
        public LINHKIEN()
        {
            this.CT_BAOCAO_TONKHO = new HashSet<CT_BAOCAO_TONKHO>();
            this.CT_HOADON = new HashSet<CT_HOADON>();
            this.CT_HOADON_NHAPHANG = new HashSet<CT_HOADON_NHAPHANG>();
            this.KHOes = new HashSet<KHO>();
        }
    
        public string MaLinhKien { get; set; }
        public string MaThuongHieu { get; set; }
        public string MaNhaCungCap { get; set; }
        public string TenLinhKien { get; set; }
        public decimal GiaBanSi { get; set; }
        public decimal GiaBanLe { get; set; }
        public string MaDonViTinh { get; set; }
        public int TinhTrang { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ThoiGianBaoHanh { get; set; }
    
        public virtual ICollection<CT_BAOCAO_TONKHO> CT_BAOCAO_TONKHO { get; set; }
        public virtual ICollection<CT_HOADON> CT_HOADON { get; set; }
        public virtual ICollection<CT_HOADON_NHAPHANG> CT_HOADON_NHAPHANG { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual ICollection<KHO> KHOes { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
