//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.BAOCAO_DOANHTHU = new HashSet<BAOCAO_DOANHTHU>();
            this.BAOCAO_TONKHO = new HashSet<BAOCAO_TONKHO>();
            this.HOADONs = new HashSet<HOADON>();
            this.HOADON_NHAPHANG = new HashSet<HOADON_NHAPHANG>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
    
        public string MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual ICollection<BAOCAO_DOANHTHU> BAOCAO_DOANHTHU { get; set; }
        public virtual ICollection<BAOCAO_TONKHO> BAOCAO_TONKHO { get; set; }
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual ICollection<HOADON_NHAPHANG> HOADON_NHAPHANG { get; set; }
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
}
